const API_ROUTES = {
	LOGIN: '/login',
	LOGOUT: '/logout',
	REGISTER: '/register',
	FORGOT_PASSWORD: '/forgotPassword',
	RESET_PASSWORD: '/resetPassword',
	VERIFY_CODE: '/verifyCode',
	TRENDING_BOOKS: '/trendingBooks',
	BOOKS: '/books',
	USER_DIGITAL_BOOKS: '/userDigitalBooks',
	AUTHORS: '/authors',
	CATEGORIES: '/categories',
	NEWS: '/news',
	LAST_NEWS: '/latestNews',
	CHANNELS: '/channels',
	AUDIOBOOKS: '/audioBooks',
	USER_AUDIOBOOKS: '/userAudioBooks',
	BEST_AUDIOBOOKS: '/bestAudioBooks',
	RECOMMENDED_CHANNELS: '/recommendedChannels',
	RECOMMENDED_EPISODES: '/recommendedEpisodes',
	CART: '/cart',
	CART_ADD: '/cart/add',
	CART_REMOVE: '/cart/remove',
	CART_UPDATE_QUANTITY: '/cart/updateQuantity',
	COUNTRIES: '/countries',
	ADDRESSES: '/addresses',
	ADDRESSES_STORE: '/addresses/store',
	ADDRESSES_UPDATE: '/addresses/update',
	ADDRESSES_DELETE: '/addresses/delete',
	ADDRESSES_SET_DEFAULT: '/addresses/setDefault',
	LANG_GET: '/user/lang/get',
	LANG_SET: '/user/lang/set',
	TERMS: '/terms',
	ORDERS: '/orders',
	PAYMENT_METHODS: '/paymentMethods',
	BANNERS: '/banners',
	USER_INFO: '/userInfo',
	USER_INFO_UPDATE: '/userInfo/update',
	NOTIFICATIONS: '/notifications',
}

export default API_ROUTES
