import { StyleSheet } from 'react-native'
import { RH, RW } from '@/theme'

const spacings = StyleSheet.create({
	mt_a: { marginTop: 'auto' },
	mt_2: { marginTop: RH(2) },
	mt_4: { marginTop: RH(4) },
	mt_10: { marginTop: RH(10) },
	mt_12: { marginTop: RH(12) },
	mt_14: { marginTop: RH(14) },
	mt_16: { marginTop: RH(16) },
	mt_18: { marginTop: RH(18) },
	mt_20: { marginTop: RH(20) },
	mt_25: { marginTop: RH(25) },
	mt_30: { marginTop: RH(30) },
	mt_45: { marginTop: RH(45) },

	ml_a: { marginLeft: 'auto' },
	ml_0: { marginLeft: RH(0) },
	ml_2: { marginLeft: RH(2) },
	ml_4: { marginLeft: RH(4) },
	ml_6: { marginLeft: RH(6) },
	ml_8: { marginLeft: RH(8) },
	ml_10: { marginLeft: RH(10) },
	ml_12: { marginLeft: RH(12) },
	ml_14: { marginLeft: RH(14) },
	ml_16: { marginLeft: RH(16) },
	ml_18: { marginLeft: RH(18) },
	ml_20: { marginLeft: RH(20) },

	mr_a: { marginRight: 'auto' },
	mr_0: { marginRight: RH(0) },
	mr_2: { marginRight: RH(2) },
	mr_4: { marginRight: RH(4) },
	mr_6: { marginRight: RH(6) },
	mr_8: { marginRight: RH(8) },
	mr_10: { marginRight: RH(10) },
	mr_12: { marginRight: RH(12) },
	mr_14: { marginRight: RH(14) },
	mr_16: { marginRight: RH(16) },
	mr_18: { marginRight: RH(18) },
	mr_20: { marginRight: RH(20) },
	mr_24: { marginRight: RH(24) },

	mb_a: { marginBottom: 'auto' },
	mb_0: { marginBottom: RH(0) },
	mb_2: { marginBottom: RH(2) },
	mb_4: { marginBottom: RH(4) },
	mb_6: { marginBottom: RH(6) },
	mb_8: { marginBottom: RH(8) },
	mb_10: { marginBottom: RH(10) },
	mb_12: { marginBottom: RH(12) },
	mb_14: { marginBottom: RH(14) },
	mb_16: { marginBottom: RH(16) },
	mb_18: { marginBottom: RH(18) },
	mb_20: { marginBottom: RH(20) },
	mb_24: { marginBottom: RH(24) },
	mb_26: { marginBottom: RH(26) },
	mb_30: { marginBottom: RH(30) },

	mv_0: { marginVertical: RH(0) },
	mv_2: { marginVertical: RH(2) },
	mv_4: { marginVertical: RH(4) },
	mv_6: { marginVertical: RH(6) },
	mv_8: { marginVertical: RH(8) },
	mv_10: { marginVertical: RH(10) },
	mv_12: { marginVertical: RH(12) },
	mv_14: { marginVertical: RH(14) },
	mv_16: { marginVertical: RH(16) },
	mv_18: { marginVertical: RH(18) },
	mv_20: { marginVertical: RH(20) },
	mv_30: { marginVertical: RH(30) },

	mh_0: { marginHorizontal: RH(0) },
	mh_2: { marginHorizontal: RH(2) },
	mh_4: { marginHorizontal: RH(4) },
	mh_6: { marginHorizontal: RH(6) },
	mh_8: { marginHorizontal: RH(8) },
	mh_10: { marginHorizontal: RH(10) },
	mh_12: { marginHorizontal: RH(12) },
	mh_14: { marginHorizontal: RH(14) },
	mh_16: { marginHorizontal: RH(16) },

	p_2: { padding: RW(2) },
	p_4: { padding: RW(4) },
	p_6: { padding: RW(6) },
	p_8: { padding: RW(8) },
	p_10: { padding: RW(10) },
	p_12: { padding: RW(12) },
	p_14: { padding: RW(14) },
	p_16: { padding: RW(16) },
	p_18: { padding: RW(18) },
	p_20: { padding: RW(20) },

	pt_0: { paddingTop: RH(0) },
	pt_2: { paddingTop: RH(2) },
	pt_4: { paddingTop: RH(4) },
	pt_6: { paddingTop: RH(6) },
	pt_8: { paddingTop: RH(8) },
	pt_10: { paddingTop: RH(10) },
	pt_12: { paddingTop: RH(12) },
	pt_14: { paddingTop: RH(14) },
	pt_16: { paddingTop: RH(16) },
	pt_18: { paddingTop: RH(18) },
	pt_20: { paddingTop: RH(20) },
	pt_30: { paddingTop: RH(30) },
	pt_40: { paddingTop: RH(40) },

	pb_0: { paddingBottom: RH(0) },
	pb_2: { paddingBottom: RH(2) },
	pb_4: { paddingBottom: RH(4) },
	pb_6: { paddingBottom: RH(6) },
	pb_8: { paddingBottom: RH(8) },
	pb_10: { paddingBottom: RH(10) },
	pb_12: { paddingBottom: RH(12) },
	pb_14: { paddingBottom: RH(14) },
	pb_16: { paddingBottom: RH(16) },
	pb_18: { paddingBottom: RH(18) },
	pb_20: { paddingBottom: RH(20) },
	pb_25: { paddingBottom: RH(25) },
	pb_30: { paddingBottom: RH(30) },
	pb_48: { paddingBottom: RH(48) },

	pl_0: { paddingLeft: RH(0) },
	pl_2: { paddingLeft: RH(2) },
	pl_4: { paddingLeft: RH(4) },
	pl_6: { paddingLeft: RH(6) },
	pl_8: { paddingLeft: RH(8) },
	pl_10: { paddingLeft: RH(10) },
	pl_12: { paddingLeft: RH(12) },
	pl_14: { paddingLeft: RH(14) },
	pl_16: { paddingLeft: RH(16) },
	pl_18: { paddingLeft: RH(18) },
	pl_20: { paddingLeft: RH(20) },

	pr_0: { paddingRight: RH(0) },
	pr_2: { paddingRight: RH(2) },
	pr_4: { paddingRight: RH(4) },
	pr_6: { paddingRight: RH(6) },
	pr_8: { paddingRight: RH(8) },
	pr_10: { paddingRight: RH(10) },
	pr_12: { paddingRight: RH(12) },
	pr_14: { paddingRight: RH(14) },
	pr_16: { paddingRight: RH(16) },
	pr_18: { paddingRight: RH(18) },
	pr_20: { paddingRight: RH(20) },

	pv_2: { paddingVertical: RW(2) },
	pv_4: { paddingVertical: RW(4) },
	pv_6: { paddingVertical: RW(6) },
	pv_8: { paddingVertical: RW(8) },
	pv_10: { paddingVertical: RW(10) },
	pv_12: { paddingVertical: RW(12) },
	pv_14: { paddingVertical: RW(14) },
	pv_16: { paddingVertical: RW(16) },
	pv_18: { paddingVertical: RW(18) },
	pv_20: { paddingVertical: RW(20) },
	pv_30: { paddingVertical: RW(30) },

	ph_0: { paddingHorizontal: RW(0) },
	ph_10: { paddingHorizontal: RW(10) },
	ph_14: { paddingHorizontal: RW(14) },
	ph_20: { paddingHorizontal: RW(20) },

	gap_4: { gap: RW(4) },
	gap_6: { gap: RW(6) },
	gap_8: { gap: RW(8) },
	gap_10: { gap: RW(10) },
	gap_12: { gap: RW(12) },
	gap_14: { gap: RW(14) },
	gap_16: { gap: RW(16) },
	gap_18: { gap: RW(18) },
	gap_20: { gap: RW(20) },
	gap_25: { gap: RW(25) },
	gap_30: { gap: RW(30) },
	gap_34: { gap: RW(34) },
	gap_56: { gap: RW(56) },
})

export default spacings
